# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://Rishit-9.github.io"
baseurl: "/gg"
siteIcon: /media/unknown.png
siteYear: 2022
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: GG Network
serverDescription: Survival Multiplayer Minecraft server.
serverIP: ggnetworkk.aternos.me:34624
useBedrockForOnlineStatus: true


# Discord information
discordInvite: https://discord.gg/pVNSVeRe7X
discordServerID: 817003562663149578
discordChannelID: 817003564185419793


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
siteNav:
  - name: Blogs
    url: blogs
  - name: Screenshots
    url: screenshots
  - name: About
    url: about
  - name: Videos
    url: videos

# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
future: true
